---

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Max: 120

Lint/DuplicateMethods:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 200

RSpec/BeforeAfterAll:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 300

Metrics/PerceivedComplexity:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/slim-h_tag.rb
    - lib/slim-htag.rb

Naming/HeredocDelimiterNaming:
  Enabled: false

RSpec/ContextWording:
  AllowedPatterns:
    - "^and"

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

Rake/Desc:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
